version: "3.7"
services:
  frontend:
    container_name: frontend
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - hermes-network
    ports:
      - 3000:3000
networks:
  hermes-network:
    external: true
