import type { Metadata } from 'next'
import './styles/global.scss'
import Navbar from './components/navbar'
import RecoilProvider from './utils/RecoilProvider'
import { Ubuntu } from 'next/font/google'

const ubuntu = Ubuntu({ weight:['500', '700'] , display:'swap', subsets:['latin']})

export const metadata: Metadata = {
    title: 'Hermes-chat-v3',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <RecoilProvider>
            <html lang="en">
                <head>
                    <link rel="icon" href="/bird.svg" sizes="any" />
                </head>
                <body className={ubuntu.className}>
                    <Navbar/>
                    {children}
                </body>
            </html>
        </RecoilProvider>
    )
}
