import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './styles/global.scss'
import Navbar from './components/navbar'
import RecoilProvider from './utils/RecoilProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Hermes-chat-v3',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
  children: React.ReactNode
}) {
    return (
        <RecoilProvider>
            <html lang="en">
                <body className={inter.className}>
                    <Navbar/>
                    {children}
                </body>
            </html>
        </RecoilProvider>
    )
}
